### PR TITLE
asc2log: add _GNU_SOURCE define

### PR DESCRIPTION
**Pull request by neheb**
Needed for strcasestr under musl.

### CODE REVIEW

**Comment by marckleinebudde** [comment]
Which build system are you using (cmake, autotools, or plain make)? autotools and plain make should define `_GNU_SOURCE` unconditioanlly.

**Comment by neheb** [comment]
cmake

**Comment by neheb** [comment]
compile_commands.json does not include _GNU_SOURCE.

**Comment by marckleinebudde** [comment]
The check needs updating...
https://github.com/linux-can/can-utils/blob/master/CMakeLists.txt#L12

**Comment by neheb** [comment]
I tried this on my Fedora machine. Turns out, only two more places need this:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index cc13c37..3b3b8a5 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -9,11 +9,6 @@ if(NOT CMAKE_BUILD_TYPE)
   set(CMAKE_BUILD_TYPE Release)
 endif()

-check_symbol_exists(__GNU_LIBRARY__ "features.h" _GNU_SOURCE)
-if(_GNU_SOURCE)
-  add_definitions(-D_GNU_SOURCE)
-endif()
-
 set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -Wno-parentheses")
 set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fno-strict-aliasing")
 set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DSO_RXQ_OVFL=40")
diff --git a/mcp251xfd/mcp251xfd-regmap.c b/mcp251xfd/mcp251xfd-regmap.c
index 61105f0..4a5f6b5 100644
--- a/mcp251xfd/mcp251xfd-regmap.c
+++ b/mcp251xfd/mcp251xfd-regmap.c
@@ -6,6 +6,10 @@
 //               Marc Kleine-Budde <kernel@pengutronix.de>
 //

+#ifndef _GNU_SOURCE
+#define _GNU_SOURCE
+#endif
+
 #include <errno.h>
 #include <fcntl.h>
 #include <stdlib.h>
diff --git a/slcanpty.c b/slcanpty.c
index e6f1efe..91d9350 100644
--- a/slcanpty.c
+++ b/slcanpty.c
@@ -24,6 +24,10 @@
  *
  */

+#ifndef _GNU_SOURCE
+#define _GNU_SOURCE
+#endif
+
 #include <fcntl.h>
 #include <libgen.h>
 #include <stdio.h>
```

**Comment by marckleinebudde** [comment]
I've added an unconditionally definition of `_GNU_SOURCE` to cmake.

**Pull request closed without merging**
