### PR TITLE
can-j1939-kickstart.md: fix example in documentation

### PR DESCRIPTION
**Pull request by josemic**
Incorrect value of the second databyte '23'

### CODE REVIEW

**Comment by hartkopp** [comment]
That was obvious :-)
Thanks!

Can you please change the subject to:

can-j1939-kickstart.md: fix example in documentation

So that the file name and the reason of "update" becomes clear. Every commit is an update :o)

**Comment by josemic** [comment]
@hartkopp 
Title of issue changed as requested.

**Comment by hartkopp** [comment]
Haha - not bad!
But I gently asked about changing the name of the commit - and not the name of the pull request :-D

**Comment by josemic** [comment]
@hartkopp:
I edited in Github directly. Shall I sync the repo and try to change the commit name? It would surely be easyer, if I create a new pull request and a new commit by editing it in github.

**Comment by hartkopp** [comment]
Yes. I thought about renaming the commit in your josemic:patch-3 branch and then force push (push -f) this branch, which will then show up in the pull request.

**Comment by josemic** [comment]
I have update the commits name to "can-j1939-kickstart.md: fix example in documentation".

**Comment by hartkopp** [comment]
Applied.
Thanks!

**Pull request merged**
