### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by berezovskyi**
Create a sample README file populated from https://packages.debian.org/sid/can-utils

### CODE REVIEW

**Comment by marckleinebudde** [comment]
Can I add you Signed-off-by to the commit?

**Comment by berezovskyi** [comment]
Sure

**Comment by marckleinebudde** [comment]
which email address do you prefer?

**Comment by berezovskyi** [comment]
Oh I'm sorry, thought you had in a commit: andrew@berezovskiy.me

**Comment by marckleinebudde** [comment]
In the commit it says: Andrew Berezovskyi <berezovskyi@users.noreply.github.com>

**Comment by berezovskyi** [comment]
It's fine either way.

**Comment by marckleinebudde** [comment]
I've changed the author's email and pushed to master.
Thnaks.

**Pull request closed without merging**
