### PR TITLE
change {} to {0}

### PR DESCRIPTION
**Pull request by neheb**
The former throws a pedantic warning.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Review by marckleinebudde — CHANGES_REQUESTED** [review]
Looks good, one nitpick. Can you add spaces around the 0? So that it reads `= { 0 };`

**Comment by neheb** [comment]
meh.

**Comment by hartkopp** [comment]
ok - and the subject should be something more informative and not like "increase value by one"

e.g. "make struct initialization C99 compatible again"

**Review by marckleinebudde — APPROVED** [review]

**Comment by hartkopp** [comment]
I changed the subject as suggested.
Thanks Rosen.

**Pull request merged**
