### PR TITLE
Add SPDX identifiers

### PR DESCRIPTION
**Pull request by yegorich**
Signed-off-by: Yegor Yefremov <yegorslists@googlemail.com>

### CODE REVIEW

**Comment by yegorich** [comment]
@hartkopp my logic is like this: if the license text in the file has the following sentence then it is GPL-2.0-or-later:

> either version 2 of the License, or any later version.

An this is the case for the most C files in can-utils.

**Comment by hartkopp** [comment]
The stuff which was originally from Volkswagen is gpl2-or-bsd-clause3 as we intended to allow the socket API in other operating systems too.  Therefore the basic tools follow this license scheme.
What would be your suggestion for the homogenization?
I would prefer GPL2-0-only for the non-VW code instead of GPL2-or-later.

**Comment by yegorich** [comment]
Let's take `GPL-2.0-only` then so that everything is consistent with the initial license from VW. @marckleinebudde what do you think?

**Comment by marckleinebudde** [comment]
If we want to relicense the files under `GPL2-or-later`, then we have to ask the original author and all contributors.

**Comment by hartkopp** [comment]
Hi @marckleinebudde ,
we wanted to unify the current GPL* files to GPL-2.0-only and NOT to GPL2-or-later.
Would this work for you?

**Comment by marckleinebudde** [comment]
Doh! I meant `GPL-2.0-only`. But you still have to get the ACK of all authors.

**Comment by yegorich** [comment]
So we're talking about the following files:

- slcand.c
- canfdtest.c
- slcanpty.c
- jcat.c
- can-calc-bit-timing.c

You already have my ACK for re-licensing.

@ukleinek , @grandwolf, @rshanmu, @btashton, @jmahler, @umlaeute, @sgh, @jschall, @mansr, @ftheile, @olerem, @snewz, @bombilee what do you think about it?

**Comment by sgh** [comment]
Hi

I trust you guys in doing the right thing. I have no real preference, so it's 
an ACK from me as well.

onsdag den 26. juni 2019 11.26.22 CEST skrev Yegor Yefremov:
> So we're talking about the following files:
> 
> - slcand.c
> - canfdtest.c
> - slcanpty.c
> - jcat.c
> - can-calc-bit-timing.c
> 
> You already have my ACK for re-licensing.
> 
> @ukleinek , @grandwolf, @rshanmu, @btashton, @jmahler, @umlaeute, @sgh,
> @jschall, @mansr, @ftheile, @olerem, @snewz, @bombilee what do you think
> about it?


-- 
Søren Holm

**Comment by marckleinebudde** [comment]
`Acked-by: Marc Kleine-Budde <mkl@pengutronix.de>`

**Comment by hartkopp** [comment]
Oh, just detected that `slcanpty.c` was written by me ... %-)

And of course `GPL-2.0-only` is my preference too, so:

`Acked-by: Oliver Hartkopp <socketcan@hartkopp.net>`

Tnx!

**Comment by mansr** [comment]
My contribution hardly gives me the right to an opinion here, but either way, I don't care.

**Comment by umlaeute** [comment]
what's the reason to clamp it down to `GPL-2.0-only`? (as in: why do you prefer it over `GPL-2.0-or-later`?)

**Comment by snewz** [comment]
Acked-by: Sven Schmitt <sven.schmitt@gmx.net>

**Comment by olerem** [comment]
Acked-by: Oleksij Rempel <ore@pengutronix.de>

**Comment by hartkopp** [comment]
> what's the reason to clamp it down to `GPL-2.0-only`? (as in: why do you prefer it over `GPL-2.0-or-later`?)

Please check the general discussions about GPLv2 -vs- GPLv3 on the internet, e.g. the tivoization problem which makes it harder for commercial users/products.

IMHO GPLv2 serves can-utils best - and the VW code is even more relaxed with gpl2-or-bsd-clause3.

**Comment by ukleinek** [comment]
My contribution seems to be just

    03c1bacfdea8 ("can-utils: trivial: fix typos concerning "separation" and "useful"")

not sure if that is relevant enough to be able to oppose a license change. Anyhow, I'm not opposed, so:

Acked-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>

for a switch to `GPL-2.0-only`.

**Comment by btashton** [comment]
Acked-by: Brennan Ashton bashton@brennanashton.com

**Comment by umlaeute** [comment]
> Please check the general discussions about GPLv2 -vs- GPLv3 on the internet, e.g. the tivoization problem which makes it harder for commercial users/products.

well yes; tivoization is the reason i mostly switched to GPLv3 these days :-) (but then, I mostly don't really work in the industries, so my POV might be a bit "academic")

but anyhow:

Acked-By: IOhannes m zmölnig <zmoelnig@iem.at>

**Comment by ftheile** [comment]
Acked-by: Frank Theile <ftheile@grundfos.com>

**Comment by grandwolf** [comment]
I personally prefer GPL-2.0-or-later, but well, here is my:

Acked-by: Wolfgang Grandegger <wg@grandegger.com>

**Comment by jmahler** [comment]
Acked-by: Jeremiah Mahler <jmmahler@gmail.com>

**Comment by jschall** [comment]
Acked-by: Jonathan Challinger mr.challinger@gmail.com

**Comment by hartkopp** [comment]
Regarding the missing ACKs:
I tried to mail to @rshanmu to his Renesas e-mail found in his commit to this repository and it returned with "unknown user".

Now trying to reach @bombilee on his gmail adress. His last commit is five years ago.

Stay tuned ...

**Comment by bombilee** [comment]
Acked-by: Cheng-Lung Lee chenglung@gmail.com

**Comment by umlaeute** [comment]
>  I tried to mail to @rshanmu to his Renesas e-mail found in his commit to this repository and it returned with "unknown user".

https://www.linkedin.com/in/rameshshanmugasundaram/ probably this helps....

**Comment by hartkopp** [comment]
Thanks! So let's wait for some more time for feedback ...

**Comment by rshanmu** [comment]
Acked-by: Ramesh Shanmugasundaram <rashanmu@gmail.com>

Apologies for not updating my email preferences. Corrected now. Thanks @yegorich

**Comment by yegorich** [comment]
@hartkopp what is the next step? Should this PR be merged as is and the followup PR change the licenses?

**Comment by marckleinebudde** [comment]
Sounds good. Reference this PR from the new one that changes the license to `GPL-2.0-only`.

**Pull request merged**
