### PR TITLE
J1939 v6

### PR DESCRIPTION
**Pull request by mikey32905**

### CODE REVIEW

**Comment by marckleinebudde** [comment]
Hello Mikey and Kurt,

On 09/24/2015 09:33 PM, mikey32905 wrote:
>         You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/linux-can/can-utils/pull/7
> 
> 
>         Commit Summary
> 
>   * can-j1939: add libj1939.a
>   * can-j1939: add jspy 'sniffer' program
>   * can-j1939: add jsr program
>   * can-j1939: update headers with j1939
>   * can-j1939: add jacd address claim daemon

Kurt, I got this pull request of the j1939 tools from Mikey. What's the
status of the j1939, can we add it to the can-utils? Is the userspace
API stable?

Marc

-- 
Pengutronix e.K.                  | Marc Kleine-Budde           |
Industrial Linux Solutions        | Phone: +49-231-2826-924     |
Vertretung West/Dortmund          | Fax:   +49-5121-206917-5555 |
Amtsgericht Hildesheim, HRA 2686  | http://www.pengutronix.de   |

**Comment by hartkopp** [comment]
IMHO there are still some design issues for the kernel implementation we did not discuss in detail.
Therefore I would not suggest to integrate the j1939 in can-utils right now.

I would like to have some more discussion about j1939 and whether the current users feel comfortable with the API or if we should move functionality inside/outside kernel space.

Oliver

**Comment by marckleinebudde** [comment]
> Hello Mikey and Kurt,
> 
> On 09/24/2015 09:33 PM, mikey32905 wrote:
> >         You can view, comment on, or merge this pull request online at:
> > 
> >   https://github.com/linux-can/can-utils/pull/7
> > 
> > 
> >         Commit Summary
> > 
> >   * can-j1939: add libj1939.a
> >   * can-j1939: add jspy 'sniffer' program
> >   * can-j1939: add jsr program
> >   * can-j1939: update headers with j1939
> >   * can-j1939: add jacd address claim daemon
> 
> Kurt, I got this pull request of the j1939 tools from Mikey. What's the
> status of the j1939, can we add it to the can-utils? Is the userspace
> API stable?

Cool!

The userspace API/ABI is IMO stable. I had a lot of feedback from Oliver
on this, and I stripped everything I could.
The semantics underneath (in kernel space) are almost stable.

The biggest thing is that the struct sockaddr_can is enlarged by j1939,
and this got never accepted.
The current kernel patches do change the other CAN sockets' behaviour to
test not on exact size of the 'struct sockaddr', but to test a 'minimal
required size'.

The lack of extensive userbase made all arguments void.
In between, the userbase may have grown?
Given that the pull request is coming from Mikey, the need is growing
and this may be a proper time to decide on this :-)

Any decision implies that some porting to 4.2 kernel needs to be done
anyway. The latest patches I have for 3.15 are not stable yet. j1939 is
stable up to 3.12 only.

Kurt

> 
> Marc
> 
> -- 
> Pengutronix e.K.                  | Marc Kleine-Budde           |
> Industrial Linux Solutions        | Phone: +49-231-2826-924     |
> Vertretung West/Dortmund          | Fax:   +49-5121-206917-5555 |
> Amtsgericht Hildesheim, HRA 2686  | http://www.pengutronix.de   |
>

**Comment by hartkopp** [comment]
Hi Kurt,

I'm sorry but I still think that your implementation and configuration is way to complex and not intuitive.
If you look at http://elinux.org/J1939 
   $ modprobe can-j1939
   $ ip link set can0 j1939 on
still looks weird. Adding addresses to CAN interfaces is not common - and if you think about this kind of assignment, it should be implemented inside the j1939 stuff and not in af_can.c. The can-gw routing netlink API was integrated in gw.c too. IMO the sockaddr_can extension would be ok - but the other implementation should be made without af_can.[ch] changes.

I remember our discussion about the address claiming but I wonder if we really follow the requirement to only put functionality into the kernel that really has to be implemented there.

Did you take a look at https://github.com/ISOBlue/isoblue-software - which is far simpler - whether it can fulfill the basic functionalities (segmentation, etc.) to enable j1939 for Linux?

Best regards,
Oliver

**Comment by marckleinebudde** [comment]
On 09/29/2015 08:34 PM, Oliver Hartkopp wrote:
> Hi Kurt,
> 
> I'm sorry but I still think that your implementation and configuration
> is way to complex and not intuitive.
> If you look at http://elinux.org/J1939
> $ modprobe can-j1939
> $ ip link set can0 j1939 on
> still looks weird. Adding addresses to CAN interfaces is not common -
> and if you think about this kind of assignment, it should be implemented
> inside the j1939 stuff and not in af_can.c. The can-gw routing netlink
> API was integrated in gw.c too. IMO the sockaddr_can extension would be
> ok - but the other implementation should be made without af_can.[ch]
> changes.
> 
> I remember our discussion about the address claiming but I wonder if we
> really follow the requirement to only put functionality into the kernel
> that really has to be implemented there.
> 
> Did you take a look at https://github.com/ISOBlue/isoblue-software -
> which is far simpler - whether it can fulfill the basic functionalities
> (segmentation, etc.) to enable j1939 for Linux?

Can we switch to the mailinglist for the discussion.

Marc


-- 
Pengutronix e.K.                  | Marc Kleine-Budde           |
Industrial Linux Solutions        | Phone: +49-231-2826-924     |
Vertretung West/Dortmund          | Fax:   +49-5121-206917-5555 |
Amtsgericht Hildesheim, HRA 2686  | http://www.pengutronix.de   |

**Comment by marckleinebudde** [comment]
In the mean time I've ported the j1939 tools to the `j1939` branch. It will be merges soonish.

**Pull request closed without merging**
