### PR TITLE
use PRIx64

### PR DESCRIPTION
**Pull request by neheb**
This is the proper specifier for uint64_t.

### CODE REVIEW

**Comment by marckleinebudde** [comment]
This produces the following warning on amd64, gcc version 11.2.0 (Debian 11.2.0-13):
```
testj1939.c: In function ‘main’:
testj1939.c:298:40: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘__u64’ {aka ‘long long unsigned int’} [-Wformat=]
  298 |                                 printf("%016" PRIx64 " ", peername.can_addr.j1939.name);
      |                                        ^~~~~~             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                  |
      |                                                                                  __u64 {aka long long unsigned int}
In file included from testj1939.c:14:
/usr/include/inttypes.h:121:41: note: format string is defined here
  121 | # define PRIx64         __PRI64_PREFIX "x"
```

**Comment by neheb** [comment]
Strange. Looks like a cast is needed.

**Comment by marckleinebudde** [comment]
`peername.can_addr.j1939.name` is am `unsigned long long`, so why not use `llx`? Does this cause any problems with musl?

**Comment by neheb** [comment]
It’s a uint64_t. Probably should just be cast to long long to avoid these issues.

**Comment by neheb** [comment]
I wonder if the linux definition of uint64_t is leaking here. That would be a bug.

**Comment by marckleinebudde** [comment]
It _is_ a `unsinged long long`:

```
➜ (pts/30) github/can-utils (master) make CFLAGS='-save-temps' testj1939
  CCLD     testj1939
➜ (pts/30) github/can-utils (master) grep typedef testj1939.i|grep __u64
__extension__ typedef unsigned long long __u64;
typedef __u64 __le64;
typedef __u64 __be64;
typedef __u64 name_t;
```

**Comment by marckleinebudde** [comment]
...but why does `j1939cat.c` behave differently?

**Comment by neheb** [comment]
Why revert? PRIx64 is the correct way to print uint64_t

**Comment by marckleinebudde** [comment]
> PRIx64 is the correct way to print uint64_t

ACK

I was talking about reverting the patch https://github.com/linux-can/can-utils/pull/327/commits/eb9cfac9543b1d0e38164e3bcd30086c840a106c

There you introduce a `PRIx64` to print an `__u64`, which is always a `unsigned long long`.

**Comment by neheb** [comment]
I’ll check musl again. It’s uint64_t there, not __u64. Sounds like some kernel header issue.

**Comment by marckleinebudde** [comment]
The `struct sockaddr_can` comes indeed from the kernel. It's part of the `can-utils` git repo, see `include/linux/can.h`:

```
/**
 * struct sockaddr_can - the sockaddr structure for CAN sockets
 * @can_family:  address family number AF_CAN.
 * @can_ifindex: CAN network interface index.
 * @can_addr:    protocol specific address information
 */
struct sockaddr_can {
        __kernel_sa_family_t can_family;
        int         can_ifindex;
        union {
                /* transport protocol class address information (e.g. ISOTP) */
                struct { canid_t rx_id, tx_id; } tp;

                /* J1939 address information */
                struct {
                        /* 8 byte name when using dynamic addressing */
                        __u64 name;

                        /* pgn:
                         * 8 bit: PS in PDU2 case, else 0
                         * 8 bit: PF
                         * 1 bit: DP
                         * 1 bit: reserved
                         */
                        __u32 pgn;

                        /* 1 byte address */
                        __u8 addr;
                } j1939;

                /* reserved for future CAN protocols address information */
        } can_addr;
};
```

**Comment by hartkopp** [comment]
> I was talking about reverting the patch [eb9cfac](https://github.com/linux-can/can-utils/commit/eb9cfac9543b1d0e38164e3bcd30086c840a106c)

I built the code on a 64bit RasPi OS which throws a weird error too ...

**Comment by neheb** [comment]
musl 64-bit full warning output:

```
mcp251xfd/mcp251xfd-main.c: In function 'main':
mcp251xfd/mcp251xfd-main.c:67:37: warning: implicit declaration of function 'basename'; did you mean 'rename'? [-Wimplicit-function-declaration]
   67 |                         print_usage(basename(argv[0]));
      |                                     ^~~~~~~~
      |                                     rename
mcp251xfd/mcp251xfd-main.c:67:37: warning: passing argument 1 of 'print_usage' makes pointer from integer without a cast [-Wint-conversion]
   67 |                         print_usage(basename(argv[0]));
      |                                     ^~~~~~~~~~~~~~~~~
      |                                     |
      |                                     int
mcp251xfd/mcp251xfd-main.c:18:31: note: expected 'char *' but argument is of type 'int'
   18 | static void print_usage(char *prg)
      |                         ~~~~~~^~~
mcp251xfd/mcp251xfd-main.c:72:37: warning: passing argument 1 of 'print_usage' makes pointer from integer without a cast [-Wint-conversion]
   72 |                         print_usage(basename(argv[0]));
      |                                     ^~~~~~~~~~~~~~~~~
      |                                     |
      |                                     int
mcp251xfd/mcp251xfd-main.c:18:31: note: expected 'char *' but argument is of type 'int'
   18 | static void print_usage(char *prg)
      |                         ~~~~~~^~~
mcp251xfd/mcp251xfd-main.c:81:29: warning: passing argument 1 of 'print_usage' makes pointer from integer without a cast [-Wint-conversion]
   81 |                 print_usage(basename(argv[0]));
      |                             ^~~~~~~~~~~~~~~~~
      |                             |
      |                             int
mcp251xfd/mcp251xfd-main.c:18:31: note: expected 'char *' but argument is of type 'int'
   18 | static void print_usage(char *prg)
      |                         ~~~~~~^~~
[11/70] Building C object CMakeFiles/asc2log.dir/asc2log.c.o
asc2log.c: In function 'eval_canfd':
asc2log.c:282:15: warning: implicit declaration of function 'strcasestr'; did you mean 'strcasecmp'? [-Wimplicit-function-declaration]
  282 |         ptr = strcasestr(buf, tmp1);
      |               ^~~~~~~~~~
      |               strcasecmp
asc2log.c:282:13: warning: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  282 |         ptr = strcasestr(buf, tmp1);
      |             ^
asc2log.c: In function 'get_date':
asc2log.c:354:38: warning: comparison between pointer and integer
  354 |         if (strcasestr(date, " pm ") != NULL) {
      |                                      ^~
[69/70] Building C object CMakeFiles/testj1939.dir/testj1939.c.o
testj1939.c: In function 'main':
testj1939.c:298:47: warning: format '%llx' expects argument of type 'long long unsigned int', but argument 2 has type '__u64' {aka 'long unsigned int'} [-Wformat=]
  298 |                                 printf("%016llx ", peername.can_addr.j1939.name);
      |                                         ~~~~~~^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                               |                           |
      |                                               long long unsigned int      __u64 {aka long unsigned int}
      |                                         %016lx
[70/70] Linking C executable testj1939

```

most of these have been fixed elsewhere.

**Comment by neheb** [comment]
Aha. Found out why this is failing: https://github.com/torvalds/linux/blob/master/arch/mips/include/uapi/asm/types.h#L16

Now what is this __SANE_USERSPACE_TYPES__ define...

**Comment by neheb** [comment]
https://github.com/linux-can/can-utils/pull/329

**Comment by marckleinebudde** [comment]
> Aha. Found out why this is failing: https://github.com/torvalds/linux/blob/master/arch/mips/include/uapi/asm/types.h#L16

Are you (cross-)compiling for MIPS-64?

How does musl import the user space headers from the kernel?

**Comment by neheb** [comment]
yes I am. I don't think this is a musl issue. It's arch specific. see other PR.

**Comment by marckleinebudde** [comment]
I can reproduce the problem with a debian mips64 toolchain.

**Comment by marckleinebudde** [comment]
Fixed with patch https://github.com/linux-can/can-utils/pull/329 in https://github.com/linux-can/can-utils/pull/330

**Comment by marckleinebudde** [comment]
> Now what is this SANE_USERSPACE_TYPES define...

I've never stumbled over this...funny thing, powerpc64 has the same issue.

**Comment by neheb** [comment]
a grep of the linux codebase shows mips, powerpc, and alpha being affected. How strange.

**Pull request merged**
