### PR TITLE
can utils [can-j1939-install-kernel-module.md]: better explanation for adding backports, fixed typos and grammar

### PR DESCRIPTION
**Pull request by zeljkoavramovic**

### CODE REVIEW

**Comment by marckleinebudde** [comment]
Please rebase to latest master

**Comment by marckleinebudde** [comment]
Please rebase to latest master

**Comment by zeljkoavramovic** [comment]
> Please rebase to latest master

Could you please check now?

**Comment by marckleinebudde** [comment]
Ok, that's not a rebase, but at least it applied now. Thanks.

**Pull request merged**
