### PR TITLE
Replaced strcpy(if_name, argv[x])+ioctl …

### PR DESCRIPTION
**Pull request by snewz**
Replaced strcpy(if_name, argv[x])+ioctl by if_idx=if_nametoindex(argv[x]) to avoid overflows caused by long user input.

Signed-off-by: Sven Schmitt <sven.schmitt@gmx.net>

### CODE REVIEW

**Comment by marckleinebudde** [comment]
Can I add your S-o-B here? What S-o-B means is explained here [1].

Patch looks good, but the compiler throws a warning here:

    cc -O2 -Wall -Wno-parentheses -fno-strict-aliasing -Iinclude -D_FILE_OFFSET_BITS=64 -DSO_RXQ_OVFL=40 -DPF_CAN=29 -DAF_CAN=PF_CAN   isotpserver.c   -o isotpserver
    isotpserver.c: In function ‘main’:
    isotpserver.c:140:15: warning: unused variable ‘ifr’ [-Wunused-variable]
      struct ifreq ifr;
                   ^

Marc

[1]
http://lxr.free-electrons.com/source/Documentation/SubmittingPatches#L407

**Comment by snewz** [comment]
Hey Marc,

S-o-B added and commit 177f9e6722fc4e70ff600f10be287a3e6754278a fixes the warning.

Sven

**Comment by marckleinebudde** [comment]
Thanks, the user of the github commit is "Sven Schmitt <sven.schmitt@volkswagen.de>" while your S-o-B is from your gmx address. I can change the author to the gmx address while Applying the patch.

Marc

**Comment by snewz** [comment]
Please do so.

Thanks
Sven

**Comment by marckleinebudde** [comment]
index aec64a5c9e61..a0b9bbbfb25d 100644
    --- a/cansend.c
    +++ b/cansend.c
    @@ -94,13 +94,14 @@ int main(int argc, char **argv)
                return 1;
        }

    -   addr.can_family = AF_CAN;
    -
    -   strcpy(ifr.ifr_name, argv[1]);
    -   if (ioctl(s, SIOCGIFINDEX, &ifr) < 0) {
    -           perror("SIOCGIFINDEX");
    +   strncpy(ifr.ifr_name, argv[1], IFNAMSIZ);
    +   ifr.ifr_ifindex = if_nametoindex(ifr.ifr_name);

Why do you copy the name to ifr_ifindex and not call if_nametoindex directly, as you do in the other commands?

Marc

**Comment by snewz** [comment]
Because in cansend ifr is used later to check mtu length:

/* check if the frame fits into the CAN netdevice */
if (ioctl(s, SIOCGIFMTU, &ifr) < 0)

**Comment by marckleinebudde** [comment]
/* check if the frame fits into the CAN netdevice */
    if (ioctl(s, SIOCGIFMTU, &ifr) < 0) 

Does it use the ifr_ifindex or the ifr.ifr_name?

**Comment by snewz** [comment]
It uses the name [1]:

```C
435         case SIOCGIFMTU:
...
441                 dev_load(net, ifr.ifr_name);
...
```
[1] http://lxr.free-electrons.com/source/net/core/dev_ioctl.c#L435

**Comment by marckleinebudde** [comment]
Thanks. Is there a ioctl that uses the ifr.ifr_name in all three cases? If so, I'll take the patch as is.

Sidenode: This is racy, someone might rename the network interface between if_nametoindex() and the ioctl() that uses the ifr.ifr_name. And I see no simple solution for this. However, this is more of an academic problem :)

**Comment by snewz** [comment]
In isotpsniffer.c case it is used to print device name:
```C
printbuf(buffer, nbytes, color?2:0, timestamp, format,
&tv, &last_tv, dst, s, ifr.ifr_name, head);
```

In isotptun.c case it is used for setting the tunnel device:
```C
ioctl(t, TUNSETIFF, (void *) &ifr)
```
.. and in this case the name is used also [1]:
```C
1562 static int tun_set_iff(struct net *net, struct file *file, struct ifreq *ifr)
...
1572         dev = __dev_get_by_name(net, ifr->ifr_name);
```

[1] http://lxr.free-electrons.com/source/drivers/net/tun.c#L1562

**Comment by marckleinebudde** [comment]
* isotpsniffer.c: Please remove the ifr completely, as is is not used in a syscall anymore.
* isotptun.c: is okay

**Comment by snewz** [comment]
Done in ee10198a39b9363f3ff122769e8391f4b50d2074.

**Comment by snewz** [comment]
Of course, sorry.

**Comment by marckleinebudde** [comment]
Thanks a lot, merged squashing all intermediate patches into a single commit.

**Pull request closed without merging**
